## Feature Selection

Selected features include:
- Socio-economic indicators
- Environmental conditions
- Awareness and behavior variables
- Health indicators (from KR dataset)

District identifier (sdist) is used for aggregation later.

In [1]:
import pandas as pd

In [3]:
kr_df = pd.read_stata("C:\\Users\\Arsh\\College\\Semester 5\\INT - 396\\RHPA-India\\data\\raw\\kr_data.dta", 
                      convert_categoricals=False)

ir_iter = pd.read_stata(
    "C:\\Users\\Arsh\\College\\Semester 5\\INT - 396\\RHPA-India\\data\\raw\\ir_data.dta",
    convert_categoricals=False,
    chunksize=100000
)

ir_df = next(ir_iter)

In [5]:
ir_cols = [
    'sdist',

    # socio-economic
    'v106',
    'v190',

    # environment
    'v113',
    'v116',
    'v119',

    # awareness
    'v171a',
    'v157',
    'v158',
    'v159',

    # behavior
    'v463a',
    'v463b',
]

kr_cols = [
    'sdist',
    'hw70',
    'hw71',
    'hw72'
]

In [12]:
ir_selected = ir_df[ir_cols]
kr_selected = kr_df[kr_cols]
ir_selected.head()

   sdist  v106  v190  v113  v116  v119  v171a  v157  v158  v159  v463a  v463b
0      1     3     3    14    12     1    NaN     0     2     2      0      0
1      1     2     3    14    12     1    NaN     1     2     2      0      0
2      1     1     3    14    44     1    NaN     2     2     0      0      0
3      1     0     3    14    12     1    NaN     0     1     2      0      0
4      1     3     3    14    12     1    NaN     0     1     2      0      0

In [13]:
kr_selected.head()

   sdist   hw70   hw71    hw72
0      1  526.0 -207.0  9996.0
1      1  565.0  150.0  -139.0
2      1  461.0  153.0  -116.0
3      1  498.0 -224.0  9998.0
4      1  298.0 -131.0  -432.0