In [1]:
import pandas as pd

In [3]:
# KR (full)
kr_df = pd.read_stata(
    "C:\\Users\\Arsh\\College\\Semester 5\\INT - 396\\RHPA-India\\data\\raw\\kr_data.dta",
    convert_categoricals=False
)

# IR (chunked)
reader = pd.read_stata(
    "C:\\Users\\Arsh\\College\\Semester 5\\INT - 396\\RHPA-India\\data\\raw\\ir_data.dta",
    convert_categoricals=False,
    chunksize=100000
)

ir_df = next(reader)   # only first chunk for now

In [4]:
ir_cols = [
    'sdist',
    'v106', 'v190',
    'v113', 'v116', 'v119',
    'v171a', 'v157', 'v158', 'v159',
    'v463a', 'v463b'
]

kr_cols = [
    'sdist',
    'hw70', 'hw71', 'hw72'
]

ir_df = ir_df[ir_cols]
kr_df = kr_df[kr_cols]

In [5]:
ir_df = ir_df.dropna()
kr_df = kr_df.dropna()

In [13]:
# Replace invalid values with NaN
kr_df[['hw70', 'hw71', 'hw72']] = kr_df[['hw70', 'hw71', 'hw72']].replace(
    [9996, 9997, 9998, 9999],
    pd.NA
)

In [21]:
kr_df = kr_df.dropna(subset=['hw70', 'hw71', 'hw72'])

In [22]:
kr_df['health_score'] = (
    kr_df['hw70'] +
    kr_df['hw71'] +
    kr_df['hw72']
) / 3

In [30]:
kr_df['health_score'] = pd.to_numeric(kr_df['health_score'], errors='coerce')

In [31]:
kr_df = kr_df.dropna(subset=['health_score'])

In [23]:
ir_df['sanitation_score'] = (
    ir_df['v113'] +
    ir_df['v116'] +
    ir_df['v119']
) / 3

In [24]:
ir_df['education_score'] = (
    ir_df['v106'] +
    ir_df['v190']
) / 2

In [25]:
ir_df['awareness_score'] = (
    ir_df['v171a'] +
    ir_df['v157'] +
    ir_df['v158'] +
    ir_df['v159']
) / 4

In [26]:
ir_df['behavior_score'] = (
    ir_df['v463a'] +
    ir_df['v463b']
) / 2

In [27]:
ir_df.head()

,sdist,v106,v190,v113,v116,v119,v171a,v157,v158,v159,v463a,v463b,sanitation_score,education_score,awareness_score,behavior_score
33,1,0,2,11,12,1,0.0,0,0,2,0,0,8.000000,1.0,0.5,0.0
36,1,2,2,11,12,1,0.0,0,0,2,0,0,8.000000,2.0,0.5,0.0
37,1,2,2,11,12,1,0.0,0,0,0,0,0,8.000000,2.0,0.0,0.0
39,1,2,5,11,11,1,0.0,0,2,2,0,0,7.666667,3.5,1.0,0.0
42,1,2,3,11,12,1,0.0,0,1,1,0,0,8.000000,2.5,0.5,0.0

In [28]:
kr_df.head()

   sdist   hw70   hw71   hw72 health_score
1      1  565.0  150.0 -139.0        192.0
2      1  461.0  153.0 -116.0        166.0
4      1  298.0 -131.0 -432.0   -88.333333
5      1   13.0  272.0  393.0        226.0
7      1   51.0  304.0  350.0        235.0

In [32]:
kr_df['health_score'].describe()

count    198802.000000
mean       -117.516090
std         107.040219
min        -553.666667
25%        -187.333333
50%        -120.333333
75%         -51.333333
max         432.666667
Name: health_score, dtype: float64